/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CoreFundDemo } from "./CoreFundDemo";
export * as factories from "./factories";
export { CoreFundDemo__factory } from "./factories/CoreFundDemo__factory";
